### DISCUSSION TITLE
NSPanel Nextion System Data ERROR! - Solved

### DISCUSSION THREAD

**Discussion by afarago** [sairon/esphome-nspanel-lovelace-ui#32] [Show and tell]
I am adding this note for all the souls spending 24+ hours trying to upload a bigger tft to Nextion and receive a "System Data ERROR!".

Wanted to add screen restart after the device boot - in case I add a new firmware this was a good way to make sure screen starts from a clean state.
However this yielded to problems when flashing a larger tft file.
Most probably the stm32 chip and the flash was not properly written.

```yaml
esphome:
  comment: "NSPanel smart switch at dining room"
  # # DON'T DO THIS - this will ruin the upload tft process to nextion screen - when in upload mode
  # on_boot:
  #   - switch.turn_off: screen_power
  #   - switch.turn_on: screen_power

switch:
  - platform: gpio
    name: ${friendly_name} Screen Power
    id: screen_power
    entity_category: config
    disabled_by_default: true
    pin:
      number: 4
      inverted: true
```

Hope this helps someone in the future :D
