### ISSUE TITLE
Use Physical Buttons for custom actions

### ISSUE THREAD

**Issue by sascha005** [sairon/esphome-nspanel-lovelace-ui#12]
Hi, is there a way to use the Physical Button to show a specific Card on NSPanel ? And use the second physical Button to fire an homeassistant Automation ?  I cannot feagure out how this works exactly. 

Cheers 
Sascha

**Comment by randybb** [comment]
I am using this - basically once I press a button it will popup the right page where I can do some more controls, like dimm this light,...

esp config
```yaml
binary_sensor:
  - platform: gpio
    name: ${name} Left Button
    pin:
      number: 14
      inverted: true
    on_click:
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.office_r_desk_strip
      - mqtt.publish_json:
          topic: $panel_recv_topic
          payload: |-
            root["CustomRecv"] = "event,buttonPress2,navigate.cardGrid_lights,button";
```

and then to related card just add _key:_:
```yaml
    cards:
      - type: cardGrid
        title: Lights
        key: lights
        entities: ...
```
