### ISSUE TITLE
Feedback "soft beep" on screen button touch feature

### ISSUE THREAD

**Issue by chrislauyp** [sairon/esphome-nspanel-lovelace-ui#13]
Hi there,
Anyone has got a solution?  ideally locally from esp/nextion (for most responsive audio feedback), if not via integration/automation between HA/NSP!
Thanks in advance!

**Comment by sairon** [comment]
You can use `on_incoming_message` for this, simple example (beeping only on button press events):
```yaml
  on_incoming_msg:
    then:
      if:
        condition:
          lambda: |-
            return x.rfind("event,buttonPress2", 0) == 0;
        then:
          - rtttl.play: "beep:d=4,o=5,b=100:32a6"
```
