### ISSUE TITLE
Entities below "cardMedia" not showing up

### ISSUE THREAD

**Issue by Shogun1978** [sairon/esphome-nspanel-lovelace-ui#18]
Got the NSPanel up and running, great work, thank you so far!

Currently I am struggling with the entities below the cardMedia. The media player is showing and everything is working, but no items below:

```
      - type: cardMedia
        title: Büro OG
        entity: media_player.bar
        entities:
          - entity: light.buro_og_deckenlicht
          - entity: light.buro_og_schreibtisch
          - entity: light.buro_og_standlich
```

I followed this description: [https://docs.nspanel.pky.eu/card-media/](https://docs.nspanel.pky.eu/card-media/). In the end, I want to call a script to switch trough different playlists/radio stations. Is there something I'm doing wrong?
