### ISSUE TITLE
upload_tft How?

### ISSUE THREAD

**Issue by DrJeff** [sairon/esphome-nspanel-lovelace-ui#19]
I used the service inside of HA but in GUI there is no where  to add the URL in YAML I can add the URL with quotes or without no joy, if I add a Key of "url" and the URL still no joy what am I missing?
Thanks

**Comment by DrJeff** [comment]
Not sure how or why the service call did not work. For a work around I added  this to the actual button and updated the panel that way. 
```
switch:
  # Physical relay 1
  - platform: gpio
    name: $friendly_devicename Relay 1
    id: relay_1
    pin:
      number: 22
    on_turn_on:
      - lambda: |-
             id(nspanel).upload_tft(http://nspanel.pky.eu/lui-us-p-release.tft);
```
