### ISSUE TITLE
Working Correctly?

### ISSUE THREAD

**Issue by omrishiv** [sairon/esphome-nspanel-lovelace-ui#5]
Hello,
I really appreciate taking the time to make this compatible with ESPHome. I think I have everything set up correctly? I can see MQTT messages, I have appdaemon running and the display is able to get the time and date; however, sending commands other than a page for my lights doesn't seem to work. Using the app.yaml, I don't think my changes are being persisted (no cards, screen timeout doesn't change, can't seem to get the weather on it).

I may have screwed up somewhere, I'm using HA and had to separately install appdaemon. Wondering if you might have some guidance as to why the cards I've set up in the yaml are not loading. 

```
nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
  sleepTimeout: 20
  screensaver:
    entity: weather.home
  cards:
    - type: cardEntities
      title: Lights
      entities:
        - light.office
    - type: cardAlarm
      title: Alarm
      entity: alarm_control_panel.hsgw
    - type: cardMedia
      entity: media_player.move
```

I can use the HA service to sent `pageType~cardThermo~themostat~climate.ecobee_2` and get the card displayed, but it disappears very quickly and also doesn't have an entity. Same with the alarm and media cards
